# Netlify configuration for Sheikh Isaqow Hassan Bora landing site

[build]
  command = "npm install"
  publish = "/"
  functions = "netlify/functions"

# Security and caching headers
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/apk/*"
  [headers.values]
    Content-Type = "application/vnd.android.package-archive"
    Cache-Control = "public, max-age=604800"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "0"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Ensure correct types for robots and sitemap
[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    Cache-Control = "public, max-age=3600"

# Optional: redirect /download to the APK
# [[redirects]]
#   from = "/download"
#   to = "/assets/apk/SheikhIsaqowApp-v1.0.2.apk"
#   status = 302
